apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: foo
  labels:
    app: test
spec:
  schedulerName: scheduler-for-statistics
  containers:
    - image: nginx
      name: nginx
      ports:
        - containerPort: 80
