apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-for-statistics-config
  namespace: kube-system
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1beta1
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: true
      leaseDuration: 15s
      renewDeadline: 10s
      resourceLock: leases
      resourceName: scheduler-for-statistics
      resourceNamespace: kube-system
      retryPeriod: 2s
    percentageOfNodesToScore: 0
    podInitialBackoffSeconds: 1
    podMaxBackoffSeconds: 10
    profiles:
      - schedulerName: scheduler-for-statistics
        plugins:
          preBind:
            enabled:
              - name: ScheForStat
#          filter:
#            enabled:
#              - name: yoda
#                weight: 0
#          preScore:
#            enabled:
#              - name: yoda
#          score:
#            enabled:
#              - name: yoda
#                weight: 300



---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-for-statistics
  namespace: kube-system
  labels:
    component: scheduler-for-statistics
spec:
  replicas: 1
  selector:
    matchLabels:
      component: scheduler-for-statistics
  template:
    metadata:
      labels:
        component: scheduler-for-statistics
    spec:
      serviceAccount: scheduler-for-statistics-sa
      priorityClassName: system-cluster-critical
      volumes:
        - name: scheduler-config
          configMap:
            name: scheduler-for-statistics-config
      containers:
        - name: scheduler-for-statistics
          image: wm775825/scheduler-for-statistics:v0
          imagePullPolicy: IfNotPresent
#          livenessProbe:
#            failureThreshold: 8
#            httpGet:
#              host: 127.0.0.1
#              path: /healthz
#              port: 10259
#              scheme: HTTPS
#            initialDelaySeconds: 15
#            timeoutSeconds: 15
          args:
            - scheduler-for-statistics
            - --config=/scheduler/scheduler-config.yaml
            - --v=5
#            - --log-dir=/tmp/scheduler-logs
          resources:
            requests:
              cpu: "300m"
          volumeMounts:
            - name: scheduler-config
              mountPath: /scheduler



---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: scheduler-for-statistics-cr
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
      - events
    verbs:
      - create
      - get
      - update
  - apiGroups:
      - ""
    resourceNames:
      - scheduler-for-statistics
    resources:
      - endpoints
    verbs:
      - delete
      - get
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - delete
      - get
      - list
      - watch
      - update
  - apiGroups:
      - ""
    resources:
      - bindings
      - pods/binding
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - pods/status
    verbs:
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - replicationcontrollers
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
      - extensions
    resources:
      - replicasets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
      - persistentvolumes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "storage.k8s.io"
    resources:
      - storageclasses
      - csinodes
    verbs:
      - watch
      - list
      - get
  - apiGroups:
      - "coordination.k8s.io"
    resources:
      - leases
    verbs:
      - create
      - get
      - list
      - update
  - apiGroups:
      - "events.k8s.io"
    resources:
      - events
    verbs:
      - create
      - patch
      - update
  - apiGroups:
      - "core.run-linux.com"
    resources:
      - scvs
    verbs:
      - delete
      - get
      - list
      - watch
      - update
      - patch
      - create


---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: scheduler-for-statistics-sa
  namespace: kube-system


---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: scheduler-for-statistics-crb
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: scheduler-for-statistics-cr
subjects:
  - kind: ServiceAccount
    name: scheduler-for-statistics-sa
    namespace: kube-system
